# Generated by Django 4.2.14 on 2024-07-31 13:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Extraction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('extraction_date', models.DateTimeField(verbose_name='date extracted')),
                ('extraction_name', models.CharField(max_length=200)),
                ('extraction_method', models.CharField(choices=[('ethanol precipitation', 'ethanol precipitation'), ('phenol chloroform', 'phenol chloroform'), ('silica', 'silica')], default='ethanol precipitation', max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Sample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sample_name', models.CharField(max_length=200)),
                ('taxon_id', models.CharField(max_length=20)),
                ('scientific_name', models.CharField(max_length=200)),
                ('date_collected', models.DateTimeField(verbose_name='date collected')),
                ('Sample_Img', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='Sequencing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequencing_date', models.DateTimeField(verbose_name='date sequenced')),
                ('mean_read_length', models.FloatField(default=0)),
                ('file_name', models.CharField(max_length=200)),
                ('sequencing_method', models.CharField(choices=[('illuming', 'illuming'), ('oxford namopore', 'oxford namopore'), ('pacbio', 'pacbio')], default='illuming', max_length=25)),
                ('extraction', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='LIMS.extraction')),
            ],
        ),
        migrations.CreateModel(
            name='QC',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quality_distribution', models.FloatField(default=0)),
                ('ambiguous_base_content', models.FloatField(default=0)),
                ('passQC', models.BooleanField(default=False)),
                ('extraction', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='LIMS.extraction')),
            ],
        ),
        migrations.AddField(
            model_name='extraction',
            name='sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='LIMS.sample'),
        ),
    ]
