# Generated by Django 4.2.14 on 2024-08-01 14:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIMS', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sample',
            name='sample_name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
