# Generated by Django 4.2.14 on 2024-08-01 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LIMS', '0002_alter_sample_sample_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample',
            name='common_name',
            field=models.CharField(default='', max_length=200),
        ),
    ]
